### ISSUE TITLE
Investigation of using asynchronous native startAsync API

### ISSUE THREAD

**Issue by huningxin** [intel/inference-engine-node#1]
startAsync: https://docs.openvinotoolkit.org/latest/classInferenceEngine_1_1InferRequest.html#a405293e8423d82a5b45f642a3bef0d24

**Comment by artyomtugaryov** [comment]
Have you got a proposal for this functionality? I've implemented `startAsync` using callback in my repo. You can  find using in [async sample](https://github.com/artyomtugaryov/inference_engine_js/blob/master/samples/async_hello_classification.ts). We can do the same in this project

**Comment by huningxin** [comment]
Thanks @artyomtugaryov , the sample of your repo looks great. Please help implement the same in this project.

**Comment by lionkunonly** [comment]
Thanks for the suggestions, @artyomtugaryov . I pushed the PR #59 . But I also find one problem and I write about it in the PR.
