### ISSUE TITLE
What is the license of hello_classification_electron/main.js 

### ISSUE THREAD

**Issue by ibelem** [intel/inference-engine-node#12]
Hi @lionkunonly, what's the license of hello_classification_electron/main.js you are using if it's from Electron upstream? Thanks

**Comment by huningxin** [comment]
I believe it is CC0: https://github.com/electron/electron-quick-start/blob/master/LICENSE.md

**Comment by ibelem** [comment]
@huningxin got it, thanks, will resolve this file as CC0 in code scan system.
