### ISSUE TITLE
A test bug on Core.getVersions('GPU')

### ISSUE THREAD

**Issue by lionkunonly** [intel/inference-engine-node#36]
In the file `test/core.js`, I try to execute the sentence `core.getVersions('GPU')` to make the GPU load the plugins in advance.  This operation leads a error like the following:
```
 TypeError: Failed to create plugin /opt/intel/openvino_2020.2.120/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so for device GPU
Please, check your environment
[CLDNN ERROR]. clGetPlatformIDs error -1001
```
The node.js API `core.getVersions()` binds the native `Core.GetVersions()` API. It seems a problem related with the OpenCL, but I do not find any information for such a error.

**Comment by huningxin** [comment]
Did you install OpenCL driver? Please refer to OpenVINO installation guide.

**Comment by lionkunonly** [comment]
Follow the installtion guide, I install the OpenCL in the correct way. This error is eliminated. Close this issue.

**Comment by chaitanyakkumar** [comment]
Can you please share the installation guide and steps you followed to eliminate the error. I am facing the same error

**Comment by artyomtugaryov** [comment]
Hello @chaitanyakkumar  you can find instruction here: https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_linux.html#optional-steps-for-intel-processor-graphics-gpu
