### ISSUE TITLE
Add getAvailableDevices into Core interface

### ISSUE THREAD

**Issue by huningxin** [intel/inference-engine-node#5]
It maps to [`Core::GetAvailableDevices`](https://docs.openvinotoolkit.org/latest/classInferenceEngine_1_1Core.html#acb212aa879e1234f51b845d2befae41c). The JS API sketch could be
```webidl
partial interface Core {
  sequence<DOMString> getAvailableDevices();
};
```

**Comment by lionkunonly** [comment]
@dkurt Hi, dkurt. Do you know why the log `[E:] [BSL] found 0 ioexpander device`  is printed when I use [`Core::GetAvailableDevices`](https://docs.openvinotoolkit.org/latest/classInferenceEngine_1_1Core.html#acb212aa879e1234f51b845d2befae41c) on my computer?

**Comment by dkurt** [comment]
Hi! We also observe it in OpenCV. Not sure if it is a bug inside Inference Engine or not.
