### ISSUE TITLE
Add PreProcessInfo interface and preProcess property into InputInfo interface

### ISSUE THREAD

**Issue by huningxin** [intel/inference-engine-node#6]
It maps to [`PreProcessInfo`](https://docs.openvinotoolkit.org/latest/classInferenceEngine_1_1PreProcessInfo.html). It allows to setup input color format, resize algorithm and others. The possible usage could be:
```js
input_info.preProcess.setResizeAlgorithm('resize-bilinear');
input_info.preProcess.setColorFormat('rgbx');
```

**Comment by lionkunonly** [comment]
Does this issue can be closed?

**Comment by huningxin** [comment]
Yes. Thanks for fixing it.
